### ISSUE TITLE
🐛  Upload latest release to PyPi

### ISSUE THREAD

**Issue by pedrocamargo** [e-lo/GMNSpy#32]
Projects (and more importantly, CI pipelines) relying on GMNSpy currently have to install it from github instead of PyPI, which is not a workflow allowed in Python's current build standard using pyproject.toml

**Comment by e-lo** [comment]
Oops - thought I had fixed but realized i had a workflow file that relied on a CLI tagging for release and I did it via github UX.  Should be resolved now (and in future): https://pypi.org/manage/project/gmnspy/release/0.3.1/

LMK if continue to be issues
